const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

// android/ is generated (CNG) and gitignored, so this file must be written
// on every prebuild rather than committed directly. JDK 24+ breaks AGP's
// CMake configure step (JEP 472 native-access warnings corrupt tool-output
// parsing); pinning the Gradle daemon to a discovered JDK 21 makes the
// shell's default java irrelevant. See docs/POLISH.md field-test readiness.
const PROPERTIES = `# Generated by plugins/withGradleDaemonJvm.js — do not edit by hand.
toolchainVersion=21
`;

module.exports = function withGradleDaemonJvm(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const gradleDir = path.join(cfg.modRequest.platformProjectRoot, 'gradle');
      fs.mkdirSync(gradleDir, { recursive: true });
      fs.writeFileSync(path.join(gradleDir, 'gradle-daemon-jvm.properties'), PROPERTIES);
      return cfg;
    },
  ]);
};
